version: '2'

services:
  api:
    container_name: nap-api
    build:
      context: ./apps/api
    volumes:
      - ./apps/api/:/var/project
    ports:
      - "3000:3000"
    working_dir: /var/project
    command: /bin/sh -c "yarn && yarn start"

  webstore:
    container_name: nap-webstore
    build:
      context: ./apps/webstore
    volumes:
      - ./apps/webstore:/var/project
    ports:
      - "3100:3100"
    links:
      - api
    working_dir: /var/project
    command: /bin/sh -c "yarn && yarn build && yarn start"
