files:
  include:
    - 'common/*.s+(a|c)ss'
    - 'components/*.s+(a|c)ss'
    - 'pages/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:

  # warnings

  # scss structure
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  border-zero:
    - 1
    - convention: '0'
  no-mergeable-selectors: 1
  no-important: 1
  placeholder-in-extend: 1

  # errors

  # scss structure
  indentation:
    - 2
    - size: 2
  brace-style:
    - 2
    - style: 1tbs
      allow-single-line: false
  empty-line-between-blocks:
    - 2
    - include: true
      allow-single-line-rulesets: true
  final-newline:
    - 2
    - include: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  mixins-before-declarations:
    - 2
    - exclude:
      - 'respond-to'
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  nesting-depth:
    - 2
    - max-depth: 4
  function-name-format:
    - 2
    - convention: hyphenatedlowercase
  mixin-name-format:
    - 2
    - convention: hyphenatedlowercase
  placeholder-name-format:
    - 2
    - convention: hyphenatedlowercase
  variable-name-format:
    - 2
    - convention: hyphenatedlowercase

  # css rules
  class-name-format:
    - 2
    - convention: hyphenatedbem
      convention-explanation: 'class names should follow this convention -> http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/'
  hex-length:
    - 2
    - style: long
  hex-notation:
    - 2
    - style: lowercase
  leading-zero:
    - 2
    - include: true
  no-debug: 2
  no-duplicate-properties:
    - 2
    - exclude:
      - src
  no-empty-rulesets: 2
  no-ids: 2
  no-invalid-hex: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 2
  no-url-protocols: 1
  no-vendor-prefixes: 1
  property-sort-order:
    - 2
    - ignore-custom-properties: true
      order: 'smacss'
  quotes:
    - 1
    - style: single
  shorthand-values: 2
  single-line-per-selector: 2
  space-before-bang:
    - 2
    - include: true
  space-after-bang:
    - 2
    - include: false
  space-before-colon:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon:
    - 2
    - include: true
  url-quotes: 2
  zero-unit:
    - 2
    - include: false
